/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceAndToneRouteImport } from './routes/voice-and-tone'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as TargetRouteImport } from './routes/target'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as ImageryRouteImport } from './routes/imagery'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FigmaRouteImport } from './routes/figma'
import { Route as ElementsRouteImport } from './routes/elements'
import { Route as IndexRouteImport } from './routes/index'

const VoiceAndToneRoute = VoiceAndToneRouteImport.update({
  id: '/voice-and-tone',
  path: '/voice-and-tone',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetRoute = TargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageryRoute = ImageryRouteImport.update({
  id: '/imagery',
  path: '/imagery',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FigmaRoute = FigmaRouteImport.update({
  id: '/figma',
  path: '/figma',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsRoute = ElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elements': typeof ElementsRoute
  '/figma': typeof FigmaRoute
  '/forms': typeof FormsRoute
  '/identity': typeof IdentityRoute
  '/imagery': typeof ImageryRoute
  '/patterns': typeof PatternsRoute
  '/personas': typeof PersonasRoute
  '/standards': typeof StandardsRoute
  '/target': typeof TargetRoute
  '/typography': typeof TypographyRoute
  '/voice-and-tone': typeof VoiceAndToneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elements': typeof ElementsRoute
  '/figma': typeof FigmaRoute
  '/forms': typeof FormsRoute
  '/identity': typeof IdentityRoute
  '/imagery': typeof ImageryRoute
  '/patterns': typeof PatternsRoute
  '/personas': typeof PersonasRoute
  '/standards': typeof StandardsRoute
  '/target': typeof TargetRoute
  '/typography': typeof TypographyRoute
  '/voice-and-tone': typeof VoiceAndToneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elements': typeof ElementsRoute
  '/figma': typeof FigmaRoute
  '/forms': typeof FormsRoute
  '/identity': typeof IdentityRoute
  '/imagery': typeof ImageryRoute
  '/patterns': typeof PatternsRoute
  '/personas': typeof PersonasRoute
  '/standards': typeof StandardsRoute
  '/target': typeof TargetRoute
  '/typography': typeof TypographyRoute
  '/voice-and-tone': typeof VoiceAndToneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elements'
    | '/figma'
    | '/forms'
    | '/identity'
    | '/imagery'
    | '/patterns'
    | '/personas'
    | '/standards'
    | '/target'
    | '/typography'
    | '/voice-and-tone'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elements'
    | '/figma'
    | '/forms'
    | '/identity'
    | '/imagery'
    | '/patterns'
    | '/personas'
    | '/standards'
    | '/target'
    | '/typography'
    | '/voice-and-tone'
  id:
    | '__root__'
    | '/'
    | '/elements'
    | '/figma'
    | '/forms'
    | '/identity'
    | '/imagery'
    | '/patterns'
    | '/personas'
    | '/standards'
    | '/target'
    | '/typography'
    | '/voice-and-tone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElementsRoute: typeof ElementsRoute
  FigmaRoute: typeof FigmaRoute
  FormsRoute: typeof FormsRoute
  IdentityRoute: typeof IdentityRoute
  ImageryRoute: typeof ImageryRoute
  PatternsRoute: typeof PatternsRoute
  PersonasRoute: typeof PersonasRoute
  StandardsRoute: typeof StandardsRoute
  TargetRoute: typeof TargetRoute
  TypographyRoute: typeof TypographyRoute
  VoiceAndToneRoute: typeof VoiceAndToneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-and-tone': {
      id: '/voice-and-tone'
      path: '/voice-and-tone'
      fullPath: '/voice-and-tone'
      preLoaderRoute: typeof VoiceAndToneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target': {
      id: '/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof TargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagery': {
      id: '/imagery'
      path: '/imagery'
      fullPath: '/imagery'
      preLoaderRoute: typeof ImageryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figma': {
      id: '/figma'
      path: '/figma'
      fullPath: '/figma'
      preLoaderRoute: typeof FigmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements': {
      id: '/elements'
      path: '/elements'
      fullPath: '/elements'
      preLoaderRoute: typeof ElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElementsRoute: ElementsRoute,
  FigmaRoute: FigmaRoute,
  FormsRoute: FormsRoute,
  IdentityRoute: IdentityRoute,
  ImageryRoute: ImageryRoute,
  PatternsRoute: PatternsRoute,
  PersonasRoute: PersonasRoute,
  StandardsRoute: StandardsRoute,
  TargetRoute: TargetRoute,
  TypographyRoute: TypographyRoute,
  VoiceAndToneRoute: VoiceAndToneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
